spring.application.name=glosai

groq.api.url=https://api.groq.com/openai/v1/chat/completions
groq.api.key=${GROQ_API_KEY}
groq.api.model=llama-3.3-70b-versatile
groq.api.temperature=0.2
groq.api.max-tokens=500

server.port=8080

spring.profiles.active=withdb

logging.level.org.springframework.boot.autoconfigure.logging.ConditionEvaluationReportLoggingListener=WARN
